#
#Sat Oct 10 15:33:44 UTC 2026
goog\:chromeOptions={args\=[test-type, ignore-certificate-errors, headless, --start-maximized, incognito, disable-infobars, disable-gpu, disable-default-apps, disable-popup-blocking, remote-allow-origins\=*], extensions\=[]}
acceptInsecureCerts=true
browserName=chrome
