#
#Sat Sep 12 13:07:00 UTC 2026
goog\:chromeOptions={args\=[test-type, ignore-certificate-errors, headless, --start-maximized, incognito, disable-infobars, disable-gpu, disable-default-apps, disable-popup-blocking, remote-allow-origins\=*], extensions\=[]}
acceptInsecureCerts=true
browserName=chrome
